"""Browser-backed extraction for public Douyin posts.

Douyin currently answers a plain HTTP request with a JavaScript VM challenge.
Its own public web page can still render the post in an anonymous Chromium
session and requests ``/aweme/v1/web/aweme/detail/`` with the short-lived
signatures generated by the site. This module observes that response; it does
not forge signatures, submit credentials, or persist browser state.

The dependency is optional at runtime. A missing Playwright/browser simply
returns ``None`` and lets the provider surface the original yt-dlp error.
"""

from __future__ import annotations

import asyncio
import json
import re
from contextlib import suppress
from pathlib import Path
from typing import Any

from app.core.config import settings
from app.core.logging import get_logger
from app.core.ssrf import assert_url_allowed
from app.providers.models import MediaFormat, MediaImage, NormalizedMedia

log = get_logger("slipstream.douyin_browser")

_DETAIL_PATH = "/aweme/v1/web/aweme/detail/"
_ID_RE = re.compile(r"/(?:video|note|slides)/(\d+)", re.I)
_browser_gate = asyncio.Semaphore(1)


def _browser_executable() -> str | None:
    configured = settings.DOUYIN_BROWSER_EXECUTABLE.strip()
    if configured:
        return configured if Path(configured).is_file() else None

    candidates = (
        Path("C:/Program Files/Google/Chrome/Application/chrome.exe"),
        Path("C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"),
        Path("C:/Program Files/Microsoft/Edge/Application/msedge.exe"),
        Path("/usr/bin/chromium"),
        Path("/usr/bin/chromium-browser"),
        Path("/usr/bin/google-chrome"),
    )
    return next((str(path) for path in candidates if path.is_file()), None)


async def extract_public_douyin(url: str) -> NormalizedMedia | None:
    """Return public post metadata observed in Chromium, or ``None``."""
    if not settings.DOUYIN_BROWSER_FALLBACK:
        return None

    checked = assert_url_allowed(url)
    executable = _browser_executable()
    try:
        from playwright.async_api import Response, async_playwright
    except ImportError:
        log.info("Douyin browser fallback unavailable: Playwright is not installed")
        return None

    async with _browser_gate:
        browser = None
        try:
            async with async_playwright() as playwright:
                launch: dict[str, Any] = {"headless": True}
                if executable:
                    launch["executable_path"] = executable
                browser = await playwright.chromium.launch(**launch)
                context = await browser.new_context(locale="zh-CN")
                page = await context.new_page()

                loop = asyncio.get_running_loop()
                detail: asyncio.Future[dict[str, Any]] = loop.create_future()
                response_tasks: set[asyncio.Task[None]] = set()

                async def inspect_response(response: Response) -> None:
                    if _DETAIL_PATH not in response.url or detail.done():
                        return
                    try:
                        payload = await response.json()
                    except Exception:
                        return
                    aweme = payload.get("aweme_detail") if isinstance(payload, dict) else None
                    if isinstance(aweme, dict):
                        detail.set_result(aweme)

                def on_response(response: Response) -> None:
                    task = asyncio.create_task(inspect_response(response))
                    response_tasks.add(task)
                    task.add_done_callback(response_tasks.discard)

                page.on("response", on_response)
                await page.goto(
                    checked.url,
                    wait_until="domcontentloaded",
                    timeout=settings.DOUYIN_BROWSER_TIMEOUT * 1000,
                )
                aweme = await asyncio.wait_for(
                    detail,
                    timeout=settings.DOUYIN_BROWSER_TIMEOUT,
                )
                final_url = page.url
                await context.close()
                return _normalise_aweme(checked.url, final_url, aweme)
        except TimeoutError:
            log.info("Douyin browser fallback timed out")
        except Exception as exc:
            log.info(
                "Douyin browser fallback failed: %s: %s",
                type(exc).__name__,
                " ".join(str(exc).split())[:160],
            )
        finally:
            if browser is not None:
                with suppress(Exception):
                    await browser.close()
    return None


def _normalise_aweme(original_url: str, final_url: str, aweme: dict[str, Any]) -> NormalizedMedia:
    raw_video = aweme.get("video")
    raw_author = aweme.get("author")
    raw_stats = aweme.get("statistics")
    video: dict[str, Any] = raw_video if isinstance(raw_video, dict) else {}
    author: dict[str, Any] = raw_author if isinstance(raw_author, dict) else {}
    stats: dict[str, Any] = raw_stats if isinstance(raw_stats, dict) else {}

    formats: list[MediaFormat] = []
    sources: dict[str, str] = {}
    for index, item in enumerate(video.get("bit_rate") or []):
        if not isinstance(item, dict) or item.get("is_h265") or item.get("is_bytevc1"):
            continue
        raw_address = item.get("play_addr")
        address: dict[str, Any] = raw_address if isinstance(raw_address, dict) else {}
        source = _first_public_url(address.get("url_list"))
        if not source:
            continue
        width = _as_int(address.get("width"))
        height = _as_int(address.get("height"))
        # For portrait video, users understand quality by the short edge
        # (1080x1920 is 1080p), not by the canvas height.
        quality = (
            min(value for value in (width, height) if value)
            if width and height
            else height or width
        )
        format_id = f"douyin-{quality or 'source'}-{index}"
        sources[format_id] = source
        formats.append(
            MediaFormat(
                format_id=format_id,
                ext="mp4",
                label=f"{quality}p" if quality else "Source",
                height=quality,
                width=width,
                fps=_as_float(item.get("FPS")),
                vcodec="h264",
                acodec="aac",
                filesize=_as_int(address.get("data_size")),
                tbr=(_as_int(item.get("bit_rate")) or 0) / 1000 or None,
                abr=_audio_bitrate(item),
                has_video=True,
                has_audio=True,
                protocol="https",
            )
        )

    # Some posts omit the bitrate ladder but still expose one progressive URL.
    if not formats:
        raw_address = video.get("play_addr")
        address = raw_address if isinstance(raw_address, dict) else {}
        source = _first_public_url(address.get("url_list"))
        if source:
            width = _as_int(address.get("width") or video.get("width"))
            height = _as_int(address.get("height") or video.get("height"))
            quality = (
                min(value for value in (width, height) if value)
                if width and height
                else height or width
            )
            format_id = "douyin-source"
            sources[format_id] = source
            formats.append(
                MediaFormat(
                    format_id=format_id,
                    ext="mp4",
                    label=f"{quality}p" if quality else "Source",
                    height=quality,
                    width=width,
                    vcodec="h264",
                    acodec="aac",
                    filesize=_as_int(address.get("data_size")),
                    has_video=True,
                    has_audio=True,
                    protocol="https",
                )
            )

    images = _normalise_images(aweme)
    raw_cover = video.get("cover")
    cover: dict[str, Any] = raw_cover if isinstance(raw_cover, dict) else {}
    thumbnail = _first_public_url(cover.get("url_list"))
    media_id = (
        str(aweme.get("aweme_id") or "")
        or _id_from_url(final_url)
        or _id_from_url(original_url)
    )
    duration_ms = _as_int(aweme.get("duration") or video.get("duration"))
    create_time = _as_int(aweme.get("create_time"))

    return NormalizedMedia(
        platform="douyin",
        platform_label="Douyin",
        original_url=original_url,
        media_id=media_id,
        title=str(aweme.get("desc") or aweme.get("caption") or "")[:500] or None,
        description=str(aweme.get("desc") or "")[:2000] or None,
        author=str(author.get("nickname") or author.get("unique_id") or "")[:255] or None,
        author_url=(
            f"https://www.douyin.com/user/{author['sec_uid']}" if author.get("sec_uid") else None
        ),
        thumbnail=thumbnail,
        duration=round(duration_ms / 1000) if duration_ms else None,
        upload_date=_date_from_timestamp(create_time),
        view_count=_as_int(stats.get("play_count")),
        like_count=_as_int(stats.get("digg_count")),
        media_type=(
            "image_set"
            if len(images) > 1 and not formats
            else "image"
            if images and not formats
            else "video"
        ),
        formats=formats,
        images=images,
        audio_available=bool(formats),
        extractor="douyin-browser",
        direct_sources=sources,
    )


def _normalise_images(aweme: dict[str, Any]) -> list[MediaImage]:
    out: list[MediaImage] = []
    for index, item in enumerate(aweme.get("images") or aweme.get("image_list") or []):
        if not isinstance(item, dict):
            continue
        url = _first_public_url(item.get("url_list"))
        if not url:
            continue
        out.append(
            MediaImage(
                index=index,
                url=url,
                width=_as_int(item.get("width")),
                height=_as_int(item.get("height")),
                ext="webp" if ".webp" in url.lower() else "jpg",
            )
        )
    return out


def _first_public_url(values: Any) -> str | None:
    if not isinstance(values, list):
        return None
    # Prefer a direct CDN URL over /aweme/v1/play, which may add a watermark.
    urls = [value for value in values if isinstance(value, str) and value.startswith("https://")]
    return next((value for value in urls if "douyin.com/aweme/v1/play" not in value), None)


def _id_from_url(url: str) -> str | None:
    match = _ID_RE.search(url)
    return match.group(1) if match else None


def _as_int(value: Any) -> int | None:
    try:
        return int(value) if value is not None else None
    except (TypeError, ValueError):
        return None


def _as_float(value: Any) -> float | None:
    try:
        return float(value) if value is not None else None
    except (TypeError, ValueError):
        return None


def _audio_bitrate(item: dict[str, Any]) -> float | None:
    try:
        extra = json.loads(str(item.get("video_extra") or "{}"))
        value = _as_int(extra.get("audio_bitrate"))
        return value / 1000 if value else None
    except (TypeError, ValueError, json.JSONDecodeError):
        return None


def _date_from_timestamp(timestamp: int | None) -> str | None:
    if not timestamp:
        return None
    from datetime import UTC, datetime

    return datetime.fromtimestamp(timestamp, tz=UTC).strftime("%Y%m%d")
