"""Application configuration.

Everything is environment-driven with safe defaults so the app boots with zero
configuration on a developer machine, while remaining strict in production.
"""

from __future__ import annotations

import secrets
from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import field_validator, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# repo_root/backend/app/core/config.py -> repo_root
REPO_ROOT = Path(__file__).resolve().parents[3]


def _default_env_file() -> list[str]:
    """Look for .env next to the repo root and inside backend/."""
    return [str(REPO_ROOT / ".env"), str(REPO_ROOT / "backend" / ".env")]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=_default_env_file(),
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # ---- Identity ---------------------------------------------------------
    APP_NAME: str = "Slipstream"
    APP_URL: str = "http://localhost:8000"
    DOMAIN: str = "localhost"
    ENVIRONMENT: Literal["development", "production", "test"] = "development"
    LOG_LEVEL: str = "INFO"
    LOG_JSON: bool = False

    # ---- Security ---------------------------------------------------------
    # Auto-generated in development; MUST be set explicitly in production.
    SECRET_KEY: str = ""
    SESSION_LIFETIME: int = 60 * 60 * 24 * 14  # seconds (14 days)
    SESSION_COOKIE_NAME: str = "slipstream_session"
    CSRF_COOKIE_NAME: str = "slipstream_csrf"
    COOKIE_SECURE: bool | None = None  # None -> derived from ENVIRONMENT
    COOKIE_SAMESITE: Literal["lax", "strict", "none"] = "lax"
    TRUSTED_PROXY_COUNT: int = 0
    CORS_ORIGINS: str = ""  # comma-separated; empty = same-origin only

    # ---- Database ---------------------------------------------------------
    DATABASE_URL: str = ""

    # ---- Initial admin ----------------------------------------------------
    INITIAL_ADMIN_USERNAME: str = "admin"
    INITIAL_ADMIN_EMAIL: str = "admin@slipstream.local"
    # Development fallback ONLY. Flagged as temporary in the DB; the admin is
    # forced to rotate it before any privileged action succeeds.
    INITIAL_ADMIN_PASSWORD: str = "oleg2017A!"  # noqa: S105 - documented dev fallback

    # ---- Storage ----------------------------------------------------------
    DATA_DIR: str = str(REPO_ROOT / "data")
    TEMP_DIR: str = ""
    LOG_DIR: str = ""

    # ---- Limits -----------------------------------------------------------
    MAX_FILE_SIZE: int = 2 * 1024 * 1024 * 1024  # 2 GiB
    MAX_VIDEO_DURATION: int = 60 * 60 * 3  # 3 hours (seconds)
    MAX_CONCURRENT_DOWNLOADS: int = 2
    JOB_TIMEOUT: int = 60 * 30  # seconds
    JOB_QUEUE_SIZE: int = 100
    TEMP_FILE_TTL: int = 60 * 60 * 2  # seconds a finished file stays downloadable
    CLEANUP_INTERVAL: int = 60 * 5  # seconds between cleanup sweeps
    HISTORY_RETENTION_DAYS: int = 90
    ANALYZE_TIMEOUT: int = 60  # seconds for metadata extraction

    # ---- Rate limits (requests per hour) ----------------------------------
    RATE_LIMIT_GUEST: int = 20  # analyses/hour
    RATE_LIMIT_GUEST_DOWNLOAD: int = 10
    RATE_LIMIT_USER: int = 120
    RATE_LIMIT_USER_DOWNLOAD: int = 60
    RATE_LIMIT_ADMIN: int = 1000
    RATE_LIMIT_AUTH: int = 10  # login/register attempts per hour per IP

    # ---- Feature flags ----------------------------------------------------
    REGISTRATION_ENABLED: bool = True
    GUEST_DOWNLOADS_ENABLED: bool = True
    MAINTENANCE_MODE: bool = False
    ALLOWED_PLATFORMS: str = ""  # empty = all registered providers

    # ---- Extraction -------------------------------------------------------
    FFMPEG_PATH: str = "ffmpeg"
    FFPROBE_PATH: str = "ffprobe"
    YTDLP_PROXY: str = ""
    YTDLP_USER_AGENT: str = ""
    # Douyin serves a JavaScript challenge to plain HTTP clients. When yt-dlp
    # cannot pass it, an optional real-browser fallback observes the public
    # detail response generated by Douyin's own page. Keep concurrency low: a
    # browser is deliberately much more expensive than a normal extractor.
    DOUYIN_BROWSER_FALLBACK: bool = True
    DOUYIN_BROWSER_EXECUTABLE: str = ""
    DOUYIN_BROWSER_TIMEOUT: int = 60
    ALLOW_PRIVATE_NETWORK_TARGETS: bool = False  # test-only escape hatch

    # ------------------------------------------------------------------ #
    # Validators
    # ------------------------------------------------------------------ #
    @field_validator("LOG_LEVEL")
    @classmethod
    def _upper_log_level(cls, v: str) -> str:
        return v.upper()

    @model_validator(mode="after")
    def _derive(self) -> Settings:
        data_dir = Path(self.DATA_DIR)
        if not self.TEMP_DIR:
            self.TEMP_DIR = str(data_dir / "temp")
        if not self.LOG_DIR:
            self.LOG_DIR = str(data_dir / "logs")
        if not self.DATABASE_URL:
            db_path = data_dir / "db" / "slipstream.db"
            self.DATABASE_URL = f"sqlite:///{db_path.as_posix()}"

        if self.COOKIE_SECURE is None:
            self.COOKIE_SECURE = self.ENVIRONMENT == "production"

        if not self.SECRET_KEY:
            if self.ENVIRONMENT == "production":
                raise ValueError(
                    "SECRET_KEY must be set in production. Generate one with: "
                    "python -c 'import secrets; print(secrets.token_urlsafe(48))'"
                )
            # Ephemeral dev key — sessions do not survive a restart, by design.
            self.SECRET_KEY = secrets.token_urlsafe(48)

        if self.COOKIE_SAMESITE == "none" and not self.COOKIE_SECURE:
            raise ValueError("COOKIE_SAMESITE=none requires COOKIE_SECURE=true")

        return self

    # ------------------------------------------------------------------ #
    # Convenience accessors
    # ------------------------------------------------------------------ #
    @property
    def is_production(self) -> bool:
        return self.ENVIRONMENT == "production"

    @property
    def is_test(self) -> bool:
        return self.ENVIRONMENT == "test"

    @property
    def data_path(self) -> Path:
        return Path(self.DATA_DIR)

    @property
    def temp_path(self) -> Path:
        return Path(self.TEMP_DIR)

    @property
    def log_path(self) -> Path:
        return Path(self.LOG_DIR)

    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",") if o.strip()]

    @property
    def allowed_platform_list(self) -> list[str]:
        return [p.strip().lower() for p in self.ALLOWED_PLATFORMS.split(",") if p.strip()]

    @property
    def db_is_sqlite(self) -> bool:
        return self.DATABASE_URL.startswith("sqlite")

    def ensure_directories(self) -> None:
        """Create every runtime directory the app writes to."""
        for path in (
            self.data_path,
            self.data_path / "db",
            self.temp_path,
            self.log_path,
        ):
            path.mkdir(parents=True, exist_ok=True)


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
